# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Run debug build"
    lane :debug do
      gradle(
        task: "assemble",
        build_type: "Debug"
      )
      firebase_app_distribution(
        app: "1:677026102993:android:0dc4bab41b7217dd490ff0",
        groups: "input-output",
        debug: true
      )
    end

    desc "Run release build"
    lane :release do
      gradle(
        task: "assemble",
        build_type: "Release"
      )
      firebase_app_distribution(
        app: "1:677026102993:android:dcb506f2d7f76d61490ff0",
        groups: "input-output",
        debug: false
      )
    end

    desc "Deploy a new version to the Google Play (ProductionType)"
      lane :productionDeploy do
        gradle(
          task: "bundle",
          build_type: "Release"
        )

        filePath = Dir['../app/build/outputs/bundle/prodRelease/*.aab'].last
        artifactPath = filePath.sub("..",".")
        puts artifactPath

        upload_to_play_store(
            track: "internal",
            package_name: "com.tydev.calorietracker.prod",
            aab: artifactPath,
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true,
            skip_upload_apk: true,
            release_status: "inProgress",
            rollout: "1"
        )
      end
end
